CREATE TABLE profile_decisions (
 actor_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
 target_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
 decision VARCHAR(4) NOT NULL CHECK (decision IN ('LIKE','PASS')),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 PRIMARY KEY(actor_id,target_id), CHECK(actor_id <> target_id)
);
CREATE TABLE collaboration_matches (
 id UUID PRIMARY KEY,
 member_a UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
 member_b UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
 compatibility INTEGER NOT NULL CHECK(compatibility > 50 AND compatibility <= 100),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 closed_at TIMESTAMP WITH TIME ZONE,
 UNIQUE(member_a,member_b), CHECK(member_a <> member_b)
);
CREATE TABLE collaboration_messages (
 sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 match_id UUID NOT NULL REFERENCES collaboration_matches(id) ON DELETE CASCADE,
 sender_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
 client_id UUID NOT NULL,
 body VARCHAR(1000) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE(match_id,sender_id,client_id)
);
CREATE INDEX messages_match_sequence ON collaboration_messages(match_id,sequence_id);
CREATE INDEX messages_sender_time ON collaboration_messages(sender_id,created_at);
CREATE INDEX matches_member_a ON collaboration_matches(member_a,closed_at);
CREATE INDEX matches_member_b ON collaboration_matches(member_b,closed_at);
