import { useState } from 'react'
import './App.css'
import Onboarding from './Onboarding'
import Account from './Account'
import './Account.css'
function App() {
 const [demo, setDemo] = useState(false)
 const [accountMode, setAccountMode] = useState<'signup' | 'login' | null>(null)
 return <main><nav><a href="/" className="brand">TEAM<span>FORGE</span></a><div className="nav-actions"><button className="secondary" onClick={() => { setDemo(false); setAccountMode("login") }}>Log in</button><button onClick={() => { setDemo(false); setAccountMode("signup") }}>Sign up</button></div></nav><>{accountMode ? <Account key={accountMode} initialMode={accountMode} onExit={() => setAccountMode(null)} /> : demo ? <Onboarding onExit={() => setDemo(false)} /> : <><section className="hero"><div><p className="eyebrow">YOUR NEXT GREAT PROJECT STARTS WITH GREAT PEOPLE</p><h1>Find the people<br/>you should <em>build with.</em></h1><p className="intro">Your ambition deserves a team. Find collaborators with complementary skills, shared goals, and time to make something real.</p><div className="actions"><button onClick={() => setDemo(true)}>Try demo ↗</button><a href="https://github.com/hass88-ux/teamforge">Follow development</a></div><p className="note">Interactive demo onboarding · No account required</p></div><aside aria-label="Illustrative collaborator card"><div className="card-top"><span className="avatar">AK</span><span className="tag">PROFILE PREVIEW</span></div><h2>Alex Kim</h2><p>Frontend engineer · Thoughtful product builder</p><div className="chips"><span>React</span><span>Design systems</span><span>Education</span></div><hr/><h3>The right kind of complementary</h3><p>You bring the backend. They bring the interface. Together, you turn an idea into something people can use.</p><div className="card-bottom"><span>◷ 7–10 hours / week</span><span>↗ Open to projects</span></div></aside></section><section className="principles"><article><span>01 / DISCOVER</span><h2>More than shared keywords.</h2><p>Matching will consider complementary skills, goals, working style, and availability.</p></article><article><span>02 / UNDERSTAND</span><h2>Know why you connect.</h2><p>Evidence-based explanations will show the signals behind each recommendation.</p></article><article><span>03 / BUILD</span><h2>From hello to a real team.</h2><p>Projects, conversations, and team recommendations will help you take the next step.</p></article></section></>}</><footer>TEAMFORGE · Development preview · Demo onboarding available · Demo discovery available · Real accounts, discovery, matches & messaging available locally.</footer></main>
}
export default App
