import { useEffect, useState } from 'react'
import { accountRequest } from './accountApi'
import RealConversation from './RealConversation'
import type { RealMatch } from './RealConversation'
type Data = { matches: RealMatch[]; projects: { id: string; name: string; yourStatus: string; stage: string }[]; coffee: { id: string; kind: string; starts_at: string; status: string }[] }
export default function Dashboard({ name, onProfile, onDiscover, onProjects }: { name: string; onProfile: () => void; onDiscover: () => void; onProjects: () => void }) {
 const [data, setData] = useState<Data | null>(null), [error, setError] = useState(''), [attempt, setAttempt] = useState(0), [active, setActive] = useState<RealMatch | null>(null)
 useEffect(() => {
  let live = true, running = false
  async function load() { if (running) return; running = true; try { const r = await accountRequest('/api/dashboard'); if (!r.ok) throw new Error('Cannot load your dashboard. Please retry or log in again.'); const value = await r.json(); if (live) { setData(value); setError('') } } catch (e) { if (live) setError(e instanceof Error ? e.message : 'Cannot load dashboard.') } finally { running = false } }
  void load(); const timer = window.setInterval(() => { if (document.visibilityState === 'visible') void load() }, 20000)
  return () => { live = false; clearInterval(timer) }
 }, [attempt])
 if (active) return <RealConversation backLabel="Back to dashboard" match={active} onBack={() => { setActive(null); setAttempt(n => n + 1) }} onUnmatched={() => { setActive(null); setAttempt(n => n + 1) }}/>
 return <section className="onboarding dashboard"><span className="demo-label">DASHBOARD</span><h1>Welcome back, <em>{name}.</em></h1><p>People, plans, and progress—all in one place.</p><div className="actions"><button className="secondary" onClick={onProfile}>Your profile</button><button className="text-button" onClick={() => setAttempt(n => n + 1)}>Refresh dashboard</button></div>{error && <p className="error" role="alert">{error}</p>}{!data && !error && <p role="status">Loading your workspace…</p>}{data && <>{!data.matches.length && !data.projects.length && <section className="next-action"><div><h2>Find the people to build with.</h2><p>Explore collaborators, share your skills, and start with a mutual connection.</p></div><button onClick={onDiscover}>Explore collaborators ↗</button></section>}<div className="workspace-metrics"><article><span>Active matches</span><strong>{data.matches.length}</strong></article><article><span>Unread messages</span><strong>{data.matches.reduce((sum, match) => sum + (match.unreadCount || 0), 0)}</strong></article><article><span>Projects & invitations</span><strong>{data.projects.length}</strong></article><article><span>Upcoming chats</span><strong>{data.coffee.length}</strong></article></div><div className="summary-grid"><article><h2>Your conversations</h2>{!data.matches.length && <p>Mutual matches appear here when you both like each other.</p>}{data.matches.map(m => <button className="secondary" key={m.id} onClick={() => setActive(m)}><strong>{m.displayName}</strong><span> · {m.unreadCount || 0} unread</span><p>{m.lastMessage || 'Start your conversation'}</p></button>)}</article><article><h2>Upcoming coffee chats</h2>{!data.coffee.length && <p>No upcoming invitations. Plan a conversation with a match.</p>}{data.coffee.map(c => <p key={c.id}><strong>{c.kind}</strong><br/>{new Date(c.starts_at).toLocaleString()} · {c.status.toLowerCase()}</p>)}</article><article><h2>Projects & invitations</h2>{!data.projects.length && <p>Save your first idea and invite a team.</p>}{data.projects.map(p => <p key={p.id}><strong>{p.name}</strong><br/>{p.stage} · {p.yourStatus === 'INVITED' ? 'Invitation waiting for you' : p.yourStatus.toLowerCase()}</p>)}<button className="secondary" onClick={onProjects}>Manage projects</button></article></div></>}</section>
}
