import { useEffect, useRef } from 'react'

export default function HelpPanel({ onClose }: { onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialog.current?.showModal() }, [])
  return <dialog ref={dialog} className="help-dialog" aria-labelledby="help-title" onClose={onClose} onCancel={onClose}>
    <div className="actions"><h2 id="help-title">Help & privacy</h2><button className="secondary" autoFocus onClick={() => dialog.current?.close()}>Close</button></div>
    <details open><summary>How do matches work?</summary><p>Select the skills you offer and need, and your provider, seeker, or collaborator intent. Providers match seekers or collaborators; seekers match providers or collaborators. Collaborators can match any intent. Discovery shows compatibility above 50%. Real conversations open only when both people like each other. Scores describe compatibility signals, rather than guaranteeing a successful partnership.</p></details>
    <details><summary>What can other people see?</summary><p>Real profiles start private. Discovery visibility shares your collaboration profile with signed-in members. Active matches can still see your public profile when you hide discovery. Your email, timezone, selected availability slots, password, and recovery key are not public. GitHub links and public project history are details you choose to share; private projects are shared with their invited team.</p></details>
    <details><summary>What happens in the demo?</summary><p>The demo is separate from real accounts. It uses sample profiles, simulated matches, and labeled automated replies. Demo choices and conversations are temporary and disappear when you reload or leave the demo.</p></details>
    <details><summary>How do I manage contact?</summary><p>Unmatch or block from a real conversation to end contact. Blocking also prevents discovery in either direction. You can remove your own blocks in Account settings; old conversations stay closed. Shared projects are separate: leave the project or ask its owner to remove membership. Reports are recorded privately in this development preview; there is no staffed moderation or emergency support.</p></details>
    <details><summary>How do I recover or delete my account?</summary><p>Generate a private recovery key in Account settings after confirming your password, then save it somewhere secure. A key is shown once and can reset your password once; generating another replaces it. Email recovery is unavailable. Download my data exports your own records. Permanent deletion requires your password and confirmation, and removes related records and owned projects, including teammates' access to those projects.</p></details>
    <details><summary>Where is my data stored?</summary><p>This local development version stores real account data on the computer running the app. Messages and project activity persist until account deletion; no automatic retention schedule is configured. Sessions expire and backend restarts require signing in again. There is no public hosted service yet. Coffee invitations stay inside TeamForge and do not create emails, calendar events, or meeting links.</p></details>
  </dialog>
}
