import { useEffect, useRef, useState } from 'react'
import { accountRequest } from './accountApi'
type Task = { id: string; title: string; kind: string; dueDate: string | null; done: boolean; revision: number }
export default function ProjectTasks({ projectId, canEdit }: { projectId: string; canEdit: boolean }) {
 const [tasks, setTasks] = useState<Task[]>([]), [title, setTitle] = useState(''), [kind, setKind] = useState('TASK'), [dueDate, setDueDate] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [attempt, setAttempt] = useState(0)
 const retry = useRef<{ key: string; id: string } | null>(null)
 useEffect(() => { let active = true; accountRequest(`/api/projects/${projectId}/tasks`).then(async r => { if (!r.ok) throw new Error('Cannot load tasks.'); return r.json() }).then(value => { if (active) { setTasks(value); setError('') } }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [projectId, attempt])
 async function add() {
  if (busy || !title.trim()) return; setBusy(true); setError('')
  const draft = { title: title.trim(), kind, dueDate: dueDate || null }, key = JSON.stringify(draft)
  if (retry.current?.key !== key) retry.current = { key, id: crypto.randomUUID() }
  try { const r = await accountRequest(`/api/projects/${projectId}/tasks`, 'POST', { ...draft, clientId: retry.current.id }); if (!r.ok) throw new Error('Cannot add this task. Check the date and your membership; each project supports up to 100 items.'); setTitle(''); retry.current = null; setAttempt(n => n + 1) } catch (e) { setError(e instanceof Error ? e.message : 'Cannot add task.') } finally { setBusy(false) }
 }
 async function toggle(t: Task) { if (busy) return; setBusy(true); setError(''); try { const r = await accountRequest(`/api/projects/${projectId}/tasks/${t.id}`, 'PUT', { done: !t.done, revision: t.revision }); if (!r.ok) throw new Error('Task changed or access ended. Refresh tasks before retrying.'); const updated = await r.json(); setTasks(current => current.map(task => task.id === t.id ? updated : task)) } catch (e) { setError(e instanceof Error ? e.message : 'Cannot update task.') } finally { setBusy(false) } }
 const done = tasks.filter(t => t.done).length
 return <section><h4>Tasks & milestones</h4><p>{done} of {tasks.length} complete</p><progress aria-label="Project progress" max={Math.max(1, tasks.length)} value={done}/>{error && <p className="error" role="alert">{error}</p>}<button className="text-button" disabled={busy} onClick={() => setAttempt(n => n + 1)}>Refresh tasks</button>{tasks.map(t => <p key={t.id}><label><input type="checkbox" checked={t.done} disabled={!canEdit || busy} onChange={() => void toggle(t)}/> {t.title}</label><br/><small>{t.kind.toLowerCase()}{t.dueDate && ` · Due ${t.dueDate}`}</small></p>)}{canEdit && <><label className="input-label" htmlFor={`task-${projectId}`}>Task or milestone title</label><input id={`task-${projectId}`} maxLength={120} value={title} onChange={e => setTitle(e.target.value)}/><label className="input-label" htmlFor={`kind-${projectId}`}>Item type</label><select id={`kind-${projectId}`} value={kind} onChange={e => setKind(e.target.value)}><option value="TASK">Task</option><option value="MILESTONE">Milestone</option></select><label className="input-label" htmlFor={`due-${projectId}`}>Due date — optional</label><input id={`due-${projectId}`} type="date" value={dueDate} onChange={e => setDueDate(e.target.value)}/><button disabled={busy || !title.trim()} onClick={() => void add()}>Add item</button></>}</section>
}
